/** @type {import('jest').Config} */
module.exports = {
    preset: 'ts-jest',
    testEnvironment: 'node',
    roots: ['<rootDir>/test'],
    testMatch: ['**/*.test.ts'],
    moduleNameMapper: {
        // the native binding is not loadable in a test run
        '^node-libcurl$': '<rootDir>/test/stubs/node-libcurl.ts',
        // src/config.ts is generated by configure.js and is not in the repository
        '^\\./config$': '<rootDir>/test/stubs/config.ts'
    },
    clearMocks: true,
    // the probe route leaves a request hanging when the upstream returns a
    // non-200 (see index.test.ts), which keeps a socket open past the run
    forceExit: true
};
